# Generated by Django 4.2.6 on 2023-10-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalprice',
            field=models.FloatField(default=0.0),
        ),
    ]
