# Generated by Django 4.2.6 on 2023-10-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_totalprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totalprice',
            new_name='total',
        ),
    ]
